### ISSUE TITLE
Run litmus tests again

### ISSUE THREAD

**Issue by mar10** [mar10/wsgidav#128]
The litmus tests on Travis are currently disabled (see #80).

Another approach could be to use Docker. The idea would be to run litmus inside a container, against WsgDAV running on the host.

An image exists here: 
    https://hub.docker.com/r/mar10/docker-litmus/
but still have to figure out, how to access it:
    https://stackoverflow.com/questions/51666589/access-a-host-from-within-a-docker-container-on-windows

Ideally the solution should allow to run the Linux-based container on Windows 10.

**Comment by fngx** [comment]
I'm running ubuntu 18.04, which also fails to compile `litmus` since SSL is enabled.

When running litmus alpine container, the wsgidav container is accessible within the bridged network, using its service name declared in docker-compose file

```
docker network ls
```

So I was able to reach the service associated to the wsgidav container, by running :

```
docker run --network=wsgidav_local --rm mar10/litmus http://wsgidav:8080
```

Regarding travis, it could be easier to put everything in a dedicated docker-compose -dev file, then run travis on top of that one.

But prior to it, I think `docker-compose includes` would be nice feature to have here
https://github.com/docker/compose/issues/318

**Comment by mar10** [comment]
https://hub.docker.com/r/mar10/docker-litmus/ can now be used to test a locally installed debug version of WsgiDAV.
Still need to integrate this into unit tests and travis

**Comment by fngx** [comment]
Nice,

I was able to run a container using your repository image (running nicely in travis builds as well) against wsgidav:

```
docker run --network=wsgidav_local --rm -ti mar10/docker-litmus \
http://wsgidav:8080/ tester secret
```

I'd still need to figure a way for integrating docker build from_cache and docker-compose to travis, along with your existing tests.

**Comment by fngx** [comment]
Got some success integrating docker-compose with travis (without caching for now, since the build is still small)

https://github.com/fngx/wsgidav/pull/3,
https://travis-ci.com/fngx/wsgidav/jobs/145194040

Both tests (tox and litmus) seem to fail though. I will look into them out of curiosity.

I also had a few issues with yaml and json configs when declaring shares / access control resulting in some obscure (to me at least) error messages, I still need to figure out.

**Comment by mar10** [comment]
Cool! Thanks for digging in.

I have seen [all tests passing](https://github.com/mar10/wsgidav/blob/master/tests/litmus.log) litmus when running from the docker-litmus container against a local wsgidav running in a virtualenv. Worked with SSL and authentication (only skipping the 'expect100' test).
I used [this config](https://github.com/mar10/wsgidav/blob/master/tests/wsgidav-litmus.yaml) and then 

    wsgidav --config tests\wsgidav-litmus.yaml -H <HOST_IP>

and

    docker run --rm -ti mar10/docker-litmus https://<HOST_IP>:8080/ tester secret

What errors did you see with yaml?

**Comment by mar10** [comment]
Could it be that the problems arise because the current unit test server and docker-compose both use port 8080?

**Comment by fngx** [comment]
Thanks, I now have a better view of what tox and litmus are doing, separately, as well as a base yaml config.

> Could it be that the problems arise because the current unit test server and docker-compose both use port 8080?

Yes you're right. Sorry, it was a very basic error, and running `docker-compose build` should have prevented it.
Ideally, everything could be run from tox utility, including deployment to both python and docker repo's.

I'm still quite unfamiliar with tox, and have to setup a correct environment so I can _Hack_.
