### ISSUE TITLE
How much concurrency can this project support? Where is the login user name recorded?

### ISSUE THREAD

**Issue by changfeng98** [mar10/wsgidav#227]
How much concurrency can this project support? Where is the login user name recorded?

**Comment by dumblob** [comment]
I support this question - please remove the bot from this issue, so it can get answered properly even if rather later than sooner.

**Comment by mar10** [comment]
This cannot easily be answered, since it depends on
- server (cheroot, gevent, gunicorn, ...) and even the server version
- OS (macOS, Linux, Windows) and version
- Hardware (RAM, Cores, ...)
- Network characteristics (bandwidth, latency)
- DAV Client (Windows mini redirector, macOS mapping, ...)
- User behavior (copying large files, or many files, mostly browsing/reading, ...)

See here for a [possible approach](https://github.com/mar10/wsgidav/blob/master/tests/stressor/results.md).

I am closing this ticket, since a broad analysis is currently out of scope, but feel free to contribute your benchmark results to the project if any. I am sure we find a place in the documentation where we can show such information.

(**Note**: I removed the part 'Where is the login user name recorded?' from this issue title, since I don't understand it.
And it should be a separate topic anyway.)
